FROM alpine:3.14

RUN apk update \
    && apk add ruby-full ruby-dev alpine-sdk \
    && gem install bundler --no-ri --no-rdoc --version 1.17.2\
    && rm -rf /var/lib/apk/*

ENV APP_HOME /app
RUN mkdir $APP_HOME

WORKDIR $APP_HOME
ADD Gemfile* $APP_HOME/
RUN bundle
ADD . $APP_HOME

ENV POST_SERVICE_HOST post
ENV POST_SERVICE_PORT 5000
ENV COMMENT_SERVICE_HOST comment
ENV COMMENT_SERVICE_PORT 9292

CMD ["puma"]
