version: '3.3'
services:

  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      - reddit
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN}

  ui:
    image: ${USER_NAME}/ui:${UI_VERSION}
    ports:
      - ${PORT}:${PORT}/tcp
    networks:
      - reddit
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN}
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.ui

  post:
    image: ${USER_NAME}/post:${POST_VERSION}
    networks:
      - reddit
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN}
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post

  comment:
    image: ${USER_NAME}/comment:${COMMENT_VERSION}
    networks:
      - reddit
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN}
  # prometheus:
  #   image: unkindy/prometheus
  #   ports:
  #     - "9090:9090"
  #   volumes:
  #     - prometheus_data:/prometheus
  #   command:
  #     - '--config.file=/etc/prometheus/prometheus.yml'
  #     - '--storage.tsdb.path=/prometheus'
  #     - '--storage.tsdb.retention=1d'
  #   networks:
  #     - reddit

  # node-exporter:
  #   image: prom/node-exporter:v0.15.2
  #   user: root
  #   volumes:
  #     - /proc:/host/proc:ro
  #     - /sys:/host/sys:ro
  #     - /:/rootfs:ro
  #   command:
  #     - '--path.procfs=/host/proc'
  #     - '--path.sysfs=/host/sys'
  #     - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
  #   networks:
  #     - reddit

  # mongodb-exporter:
  #   image: bitnami/mongodb-exporter:latest
  #   environment:
  #     - MONGODB_URI=mongodb://post_db:27017
  #   ports:
  #     - "9216:9216"
  #   networks:
  #     - reddit

volumes:
  post_db:
    # prometheus_data:


networks:
  reddit:
